# Generated by Django 5.1.4 on 2024-12-30 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcechat',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='sourcechat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='source',
            field=models.TextField(default='non source', max_length=4000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='SourceChat',
        ),
    ]
