# Generated by Django 5.1.3 on 2024-11-19 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
