# Generated by Django 5.1.3 on 2024-11-29 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0002_user_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.TextField(default='Trò chuyện mới', max_length=120, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
