# Generated by Django 5.1.3 on 2024-11-29 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0003_session_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='model',
            field=models.TextField(choices=[('gemini-1.5-pro', 'gemini-1.5-pro'), ('gpt-4.o-mini', 'gpt-4.o-mini'), ('llama-3.2-3b-instruct', 'llama-3.2-3b-instruct')], default='gemini-1.5-pro'),
        ),
        migrations.AddField(
            model_name='chat',
            name='prompting',
            field=models.TextField(choices=[('zero-shot', 'zero-shot'), ('one-shot', 'one-shot'), ('few-shot', 'few-shot'), ('chai-of-thought', 'chain-of-thought')], default='zero-shot'),
        ),
        migrations.AddField(
            model_name='session',
            name='context',
            field=models.TextField(default='', max_length=4000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
