# Generated by Django 5.1.4 on 2024-12-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0004_chat_model_chat_prompting_session_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='model',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='prompting',
        ),
    ]
