# Generated by Django 5.1.4 on 2024-12-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QALLM', '0005_remove_chat_model_remove_chat_prompting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='context',
        ),
    ]
